[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "quickstar"
version = "0.1.0"
description = "A quickstart CLI app"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
quickstar = "main:cli"